name: twitter_snap_desktop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  archive: ^4.0.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.4
  json_annotation: ^4.9.0
  media_kit: ^1.1.2+1
  media_kit_libs_video: ^1.0.5
  media_kit_libs_windows_video: any
  media_kit_video: ^1.1.2
  package_info_plus: ^8.1.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.5.3
  video_player: ^2.9.2
  video_player_media_kit: ^1.0.5

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  pedantic_mono: any
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
