name: twitter_snap_desktop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^3.6.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.4
  package_info_plus: ^8.1.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
